import { Bot, FileText, Calendar, TrendingUp, Users, MessageSquare, ArrowUpRight } from 'lucide-react';
import { useState } from 'react';

const reports = [
  {
    id: '1',
    date: 'Yesterday',
    conversations: 24,
    newLeads: 8,
    appointments: 5,
    highIntentLeads: 3,
    summary: [
      'Pricing was the most common enquiry today, accounting for 38% of conversations.',
      '3 high-intent leads identified — 2 require follow-up today.',
      'Peak enquiry time was 10 AM - 12 PM with 8 conversations.',
      'Appointment booking rate improved by 15% compared to the previous day.',
    ],
  },
  {
    id: '2',
    date: '2 days ago',
    conversations: 19,
    newLeads: 5,
    appointments: 3,
    highIntentLeads: 2,
    summary: [
      'Operating hours and location were the most asked questions.',
      '2 new leads captured through website chat.',
      'All appointments were successfully confirmed by AI.',
    ],
  },
  {
    id: '3',
    date: '3 days ago',
    conversations: 28,
    newLeads: 11,
    appointments: 7,
    highIntentLeads: 5,
    summary: [
      'Highest conversation volume this week.',
      '5 high-intent leads — strongest day for lead quality.',
      'Corporate package enquiries increased significantly.',
      'AI successfully handled 92% of conversations without escalation.',
    ],
  },
];

export default function ReportsPage() {
  const [selectedReport, setSelectedReport] = useState(reports[0]);

  return (
    <div className="animate-fade-in">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4 mb-6">
        <div>
          <h1 className="text-2xl sm:text-3xl font-bold text-surface-900">AI Reports</h1>
          <p className="text-sm text-surface-500 mt-1">Daily business summaries generated by your AI analyst.</p>
        </div>
        <button className="flex items-center gap-1.5 px-4 py-2 border border-surface-200 text-surface-700 text-sm font-medium rounded-lg hover:bg-surface-50 transition-colors">
          <FileText className="w-4 h-4" /> Export Report
        </button>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-4 gap-6">
        {/* Report List */}
        <div className="lg:col-span-1 space-y-2">
          {reports.map(report => (
            <button
              key={report.id}
              onClick={() => setSelectedReport(report)}
              className={`w-full text-left p-4 rounded-xl border transition-all ${
                selectedReport.id === report.id
                  ? 'border-primary-300 bg-primary-50'
                  : 'border-surface-200 bg-white hover:border-surface-300'
              }`}
            >
              <p className="text-sm font-semibold text-surface-900">{report.date}</p>
              <div className="flex items-center gap-3 mt-2">
                <span className="text-xs text-surface-500">{report.conversations} conv.</span>
                <span className="text-xs text-surface-500">{report.newLeads} leads</span>
              </div>
            </button>
          ))}
        </div>

        {/* Report Detail */}
        <div className="lg:col-span-3">
          <div className="bg-white rounded-xl border border-surface-200 p-6">
            <div className="flex items-center gap-2 mb-6">
              <Bot className="w-5 h-5 text-primary-600" />
              <h2 className="text-lg font-bold text-surface-900">Yesterday's Business Report</h2>
            </div>

            {/* Metrics */}
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mb-8">
              {[
                { label: 'Conversations', value: selectedReport.conversations, icon: MessageSquare, color: 'text-blue-600' },
                { label: 'New Leads', value: selectedReport.newLeads, icon: Users, color: 'text-emerald-600' },
                { label: 'Appointments', value: selectedReport.appointments, icon: Calendar, color: 'text-violet-600' },
                { label: 'High Intent', value: selectedReport.highIntentLeads, icon: TrendingUp, color: 'text-rose-600' },
              ].map(metric => (
                <div key={metric.label} className="text-center p-4 bg-surface-50 rounded-xl">
                  <metric.icon className={`w-5 h-5 mx-auto mb-2 ${metric.color}`} />
                  <p className="text-2xl font-bold text-surface-900">{metric.value}</p>
                  <p className="text-xs text-surface-500 mt-0.5">{metric.label}</p>
                </div>
              ))}
            </div>

            {/* AI Summary */}
            <div className="bg-primary-50 rounded-xl border border-primary-100 p-5">
              <div className="flex items-center gap-2 mb-4">
                <Bot className="w-4 h-4 text-primary-600" />
                <h3 className="text-sm font-semibold text-primary-800">AI Summary</h3>
              </div>
              <ul className="space-y-3">
                {selectedReport.summary.map((item, idx) => (
                  <li key={idx} className="flex items-start gap-2.5">
                    <ArrowUpRight className="w-4 h-4 text-primary-500 flex-shrink-0 mt-0.5" />
                    <p className="text-sm text-primary-800 leading-relaxed">{item}</p>
                  </li>
                ))}
              </ul>
            </div>

            {/* Action Items */}
            <div className="mt-6 p-5 bg-amber-50 rounded-xl border border-amber-100">
              <h3 className="text-sm font-semibold text-amber-800 mb-3">Recommended Actions</h3>
              <ul className="space-y-2">
                <li className="flex items-center gap-2 text-sm text-amber-700">
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full" />
                  Follow up with 3 high-intent leads today
                </li>
                <li className="flex items-center gap-2 text-sm text-amber-700">
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full" />
                  Review pricing FAQ — most asked question
                </li>
                <li className="flex items-center gap-2 text-sm text-amber-700">
                  <span className="w-1.5 h-1.5 bg-amber-500 rounded-full" />
                  Confirm 2 pending appointments
                </li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
